/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    LAlertCircle: typeof import('lucide-vue-next')['AlertCircle']
    LLogOut: typeof import('lucide-vue-next')['LogOut']
    LX: typeof import('lucide-vue-next')['X']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    NotificationToast: typeof import('./src/components/common/NotificationToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
